name: "Refactor"
description: Suggest an internal refactor for code clarity or structure
labels: ["type:refactor"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this refactor necessary?
      placeholder: |
        The analyzer class is doing too many things. We should separate...
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope of Refactor
      description: Which classes or files are impacted?
      placeholder: |
        Mainly `MigrationAnalyzer.php`, and some interfaces in `Rules/`
    validations:
      required: true
